vim.keymap.set('n', '<leader>bl', function() vim.cmd('ls') end, { desc = "list buffers"})
vim.keymap.set('n', '<leader>bn', function() vim.cmd('bn') end, { desc = "buffer next"})
vim.keymap.set('n', '<leader>bp', function() vim.cmd('bp') end, { desc = "previous buffer"})
vim.keymap.set('n', '<leader>bds', function() vim.cmd('bd!') end, { desc = "delete buffer"})
vim.keymap.set('n', '<leader>bda', function() vim.cmd('bufdo bd') end, { desc = "delete all buffers"})
