return {
    "hrsh7th/nvim-cmp",
    lazy = false,
    dependencies = { 'saadparwaiz1/cmp_luasnip',
        'hrsh7th/cmp-buffer',
        'rasulomaroff/cmp-bufname',
        'uga-rosa/cmp-dictionary',
        'f3fora/cmp-spell',
        'hrsh7th/cmp-path',
        'petertriho/cmp-git',
        'Dosx001/cmp-commit',
        'hrsh7th/cmp-cmdline',
        'andersevenrud/cmp-tmux',
        'tamago324/cmp-zsh',
        'hrsh7th/cmp-copilot',
        'nat-418/cmp-color-names.nvim',
        'amarakon/nvim-cmp-fonts',
        'Jezda1337/nvim-html-css',
        'roginfarrer/cmp-css-variables',
        'Saecki/crates.nvim',
        'David-Kunz/cmp-npm',
        'vrslev/cmp-pypi',
        'Snikimonkd/cmp-go-pkgs',
        'epwalsh/obsidian.nvim',
        'jc-doyle/cmp-pandoc-references',
        'PhilippFeO/cmp-csv',
        'hrsh7th/cmp-nvim-lua',
        'ray-x/cmp-treesitter',
        'SergioRibera/cmp-dotenv',
    },
    config = function()
        local cmp = require('cmp')
        cmp.setup({
            sources = {
                { name = 'nvim_lsp' },
                { name = 'buffer' },
                { name = 'bufname' },
                { name = 'spell' },
                { name = 'path' },
                { name = 'git' },
                { name = 'commit' },
                { name = 'cmdline' },
                { name = 'tmux' },
                { name = 'zsh' },
                { name = 'copilot.vim' },
                { name = 'fonts' },
                { name = 'nvim-html-css' },
                { name = 'css-variables' },
                { name = 'crates' },
                { name = 'pypi' },
                { name = 'go packages' },
                { name = 'obsidian.nvim' },
                { name = 'cmp-csv' },
                { name = 'nvim_lua' },
                { name = 'dotenv' },
                { name = 'dictionary' },
                { name = 'color_names' },
                { name = 'npm' },
                { name = 'pandoc_references' },
                { name = 'treesitter' }
            },
            snippet = {
                expand = function(args)
                    vim.snippet.expand(args.body)
                end,
            },
            mapping = cmp.mapping.preset.insert({}),
        })
    end,
}
